In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
import matplotlib.pyplot as plt
#import seaborn as sns
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
import pandas as pd  # Importing Pandas library
import os
import numpy as np
#import csv

In [4]:
ls

 Volume in drive C is OS
 Volume Serial Number is C4DF-4290

 Directory of C:\Users\rajpr

2022-04-09  02:21 PM    <DIR>          .
2022-04-09  02:21 PM    <DIR>          ..
2022-03-19  02:17 PM    <DIR>          .android
2022-04-08  11:43 PM            18,194 .bash_history
2021-03-06  07:13 PM    <DIR>          .cache
2022-04-09  02:37 PM    <DIR>          .conda
2022-04-09  02:12 PM                43 .condarc
2022-03-27  10:55 PM    <DIR>          .docker
2022-02-03  12:22 PM    <DIR>          .eclipse
2022-03-19  05:02 PM               208 .gitconfig
2022-03-10  11:49 AM    <DIR>          .gradle
2021-08-05  02:52 PM    <DIR>          .idlerc
2022-04-04  03:51 PM    <DIR>          .ipynb_checkpoints
2020-11-25  06:29 PM    <DIR>          .ipython
2020-11-25  06:32 PM    <DIR>          .jupyter
2022-03-25  07:12 PM                20 .lesshst
2022-03-28  01:37 PM    <DIR>          .m2
2022-03-21  05:11 PM    <DIR>          .matplotlib
2021-10-21  02:46 PM    <DIR>          .mchp_packs

In [5]:
import pandas as pd
data = pd.read_csv(r"C:\Users\rajpr\Downloads\archive\diabetes-dataset.csv")

data_np=data.to_numpy()
print('NUMPY data', data_np)

print(data_np.shape)

print(data_np[1:,1])

NUMPY data [[2.00e+00 1.38e+02 6.20e+01 ... 1.27e-01 4.70e+01 1.00e+00]
 [0.00e+00 8.40e+01 8.20e+01 ... 2.33e-01 2.30e+01 0.00e+00]
 [0.00e+00 1.45e+02 0.00e+00 ... 6.30e-01 3.10e+01 1.00e+00]
 ...
 [6.00e+00 8.50e+01 7.80e+01 ... 3.82e-01 4.20e+01 0.00e+00]
 [0.00e+00 1.29e+02 1.10e+02 ... 3.19e-01 2.60e+01 1.00e+00]
 [2.00e+00 8.10e+01 7.20e+01 ... 5.47e-01 2.50e+01 0.00e+00]]
(2000, 9)
[ 84. 145. 135. ...  85. 129.  81.]


In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               2000 non-null   int64  
 1   Glucose                   2000 non-null   int64  
 2   BloodPressure             2000 non-null   int64  
 3   SkinThickness             2000 non-null   int64  
 4   Insulin                   2000 non-null   int64  
 5   BMI                       2000 non-null   float64
 6   DiabetesPedigreeFunction  2000 non-null   float64
 7   Age                       2000 non-null   int64  
 8   Outcome                   2000 non-null   int64  
dtypes: float64(2), int64(7)
memory usage: 140.8 KB


In [7]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [8]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   
2            0      145              0              0        0  44.2   
3            0      135             68             42      250  42.3   
4            1      139             62             41      480  40.7   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.127   47        1  
1                     0.233   23        0  
2                     0.630   31        1  
3                     0.365   24        1  
4                     0.536   21        0

In [9]:
data.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0

In [10]:
data.describe()

Pregnancies      Glucose  BloodPressure  SkinThickness      Insulin  \
count  2000.000000  2000.000000    2000.000000    2000.000000  2000.000000   
mean      3.703500   121.182500      69.145500      20.935000    80.254000   
std       3.306063    32.068636      19.188315      16.103243   111.180534   
min       0.000000     0.000000       0.000000       0.000000     0.000000   
25%       1.000000    99.000000      63.500000       0.000000     0.000000   
50%       3.000000   117.000000      72.000000      23.000000    40.000000   
75%       6.000000   141.000000      80.000000      32.000000   130.000000   
max      17.000000   199.000000     122.000000     110.000000   744.000000   

               BMI  DiabetesPedigreeFunction          Age      Outcome  
count  2000.000000               2000.000000  2000.000000  2000.000000  
mean     32.193000                  0.470930    33.090500     0.342000  
std       8.149901                  0.323553    11.786423     0.474498  
min       0.000000                  0.078000    21.000000     0.000000  
25%      27.375000                  0.244000    24.000000     0.000000  
50%      32.300000                  0.376000    29.000000     0.000000  
75%      36.800000                  0.624000    40.000000     1.000000  
max      80.600000                  2.420000    81.000000     1.000000

In [11]:
data.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.120405       0.149672      -0.063375   
Glucose                      0.120405  1.000000       0.138044       0.062368   
BloodPressure                0.149672  0.138044       1.000000       0.198800   
SkinThickness               -0.063375  0.062368       0.198800       1.000000   
Insulin                     -0.076600  0.320371       0.087384       0.448859   
BMI                          0.019475  0.226864       0.281545       0.393760   
DiabetesPedigreeFunction    -0.025453  0.123243       0.051331       0.178299   
Age                          0.539457  0.254496       0.238375      -0.111034   
Outcome                      0.224437  0.458421       0.075958       0.076040   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.076600  0.019475                 -0.025453   
Glucose                   0.320371  0.226864                  0.123243   
BloodPressure             0.087384  0.281545                  0.051331   
SkinThickness             0.448859  0.393760                  0.178299   
Insulin                   1.000000  0.223012                  0.192719   
BMI                       0.223012  1.000000                  0.125719   
DiabetesPedigreeFunction  0.192719  0.125719                  1.000000   
Age                      -0.085879  0.038987                  0.026569   
Outcome                   0.120924  0.276726                  0.155459   

                               Age   Outcome  
Pregnancies               0.539457  0.224437  
Glucose                   0.254496  0.458421  
BloodPressure             0.238375  0.075958  
SkinThickness            -0.111034  0.076040  
Insulin                  -0.085879  0.120924  
BMI                       0.038987  0.276726  
DiabetesPedigreeFunction  0.026569  0.155459  
Age                       1.000000  0.236509  
Outcome                   0.236509  1.000000

In [12]:
# blood pressure (predictor 1)
# patient age (predictor 2)
# skin thickness (predictor 3)
# insulin levels (predictor 4) 
# glucose level measurement (target outcome)
from sklearn.metrics import r2_score
import math
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
x = data.iloc[1:,[2,3,4,7]] #predictors
y = data.iloc[1:,1].values #outcome
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

# Fit regression model
n_neighbors = 2

knn = neighbors.KNeighborsRegressor(n_neighbors)
knn.fit(x_train, y_train)

knnTrain_predictY = knn.predict(x_train)
knnTest_predictY = knn.predict(x_test)

knn_trainR2 = r2_score(y_train, knnTrain_predictY)
knn_testR2 = r2_score(y_test, knnTest_predictY)

print("Performance of the k nearest neighbor model on training model (R^2) is: ", knn_trainR2)
print("Performance of the k nearest neighbor model on testing model (R^2) is:", knn_testR2)

knnTrain_RMSE = math.sqrt(mean_squared_error(y_train, knnTrain_predictY))
knnTest_RMSE = math.sqrt(mean_squared_error(y_test, knnTest_predictY))

print("Training Data RMSE (accuracy for regression): ", knnTrain_RMSE)
print("Testing Data RMSE (accuracy for regression): ", knnTest_RMSE)

print("knn predicted y for training: ", knnTrain_predictY)
print("knn predicted y for testing: ", knnTest_predictY)

#plt.subplot(2, 1, i + 1)
#plt.scatter(x_test[:,0], y_test[:,0], color="blue", label="data")
#plt.plot(y, y_train, color="navy", label="prediction")
#plt.axis("tight")
#plt.legend()
#plt.title("KNeighborsRegressor (k = %i, weights = '%s')" % (n_neighbors, weights))

#plt.tight_layout()
#plt.show()

Performance of the k nearest neighbor model on training model (R^2) is:  0.9080913741290846
Performance of the k nearest neighbor model on testing model (R^2) is: 0.5861035712109155
Training Data RMSE (accuracy for regression):  9.882950142041704
Testing Data RMSE (accuracy for regression):  19.89379947560942
knn predicted y for training:  [ 97. 105. 167. ... 166. 137. 165.]
knn predicted y for testing:  [108.5  90.  112.  131.5 122.  120.5  94.  128.   99.  180.5 131.  129.
 199.   92.5 148.5 182.  100.  109.5 148.5  91.  129.   91.  105.  129.
 170.  163.   72.  125.  111.   91.  108.   98.5 115.  120.5  97.  115.
 100.5 170.  178.  125.   88.  132.  128.  120.  134.5  94.5 112.   83.
 127.   84.  120.5 135.   72.  199.   83.   99.   99.   87.  112.  122.
 140.   88.5  91.   95.  111.  190.  116.  143.   89.   99.5 126.  125.
 141.  101.  103.5 144.  104.   95.5  81.  109.5 106.  184.   99.   98.
  91.  143.  135.  115.  126.   96.  173.  120.   91.5 126.  114.5 111.
 130.  125.  183